### PR TITLE
Feature/subscription weak reference

### PR DESCRIPTION
**Pull request by NailxSharipov**
also rework logic to call func "waitForSubscribe". It's useless to call it on sync queue case in its body it wrap everything in queue

### CODE REVIEW

**Comment by FZambia** [comment]
@NailxSharipov hello, both open pull requests contain almost the same changes, does it mean that only this one is now relevant?

**Comment by NailxSharipov** [comment]
This one is depend on the previous

**Comment by NailxSharipov** [comment]
If apply this the other can be deleted. Our you can apply firstly the first, and after this one

**Comment by FZambia** [comment]
@NailxSharipov could you please update this pr so it reflects real changes against master and resolve existing conflict?

**Comment by FZambia** [comment]
Thanks for beautiful refactoring.

**Comment by FZambia** [comment]
@NailxSharipov a bit busy these days, will make new release with changes very soon but not before next weekend I think.

**Pull request merged**
