### PR TITLE
migrate to StarScream 4. Use custom queue for the callbacks notifications

### PR DESCRIPTION
**Pull request by NailxSharipov**
migrate to StarScream 4
use more cleanest api for callback notifications. It makes the code more readable.

### CODE REVIEW

**Comment by FZambia** [comment]
@NailxSharipov hello, thanks! BTW - is StarScream 4.0 officially released? I am a bit confused with its [releases page](https://github.com/daltoniam/Starscream/releases) where 4.0 tag is not marked as release and there were no minor fixes since then.

**Comment by NailxSharipov** [comment]
I've just saw it in their readme file, where they suggest to use 4.0. And they have cocoapods release for it. But I don't have any other information on this case.

**Comment by FZambia** [comment]
Just found an issue https://github.com/daltoniam/Starscream/issues/724 - looks like we better to wait with migration to StarScream 4.

**Comment by NailxSharipov** [comment]
no problem

**Comment by FZambia** [comment]
Closing for now (at this point we embedded Starscream 3 to Centrifuge to avoid dependency conflicts), but the issue which tracks this will still be open and we will look for a way to migrate to some robust and maintained WS solution.

**Pull request closed without merging**
